const verses = [
  "Genesis 1:1 — In the beginning God created the heavens and the earth.",
  "Exodus 14:14 — The Lord will fight for you; you need only to be still.",
  "Leviticus 19:18 — Love your neighbor as yourself.",
  "Numbers 6:24 — The Lord bless you and keep you.",
  "Deuteronomy 31:6 — Be strong and courageous. Do not be afraid.",
  "Joshua 1:9 — Be strong and courageous. Do not be frightened.",
  "Judges 5:31 — Peace for Israel.",
  "Ruth 1:16 — Wherever you go I will go.",
  "1 Samuel 16:7 — The Lord looks at the heart.",
  "2 Samuel 22:31 — God is my rock and my fortress.",
  "1 Kings 8:57 — The Lord our God be with us.",
  "2 Kings 6:16 — The Lord is with us; do not fear.",
  "1 Chronicles 16:11 — Seek the Lord and his strength.",
  "2 Chronicles 7:14 — If my people humble themselves.",
  "Ezra 7:10 — Ezra had set his heart to study the law.",
  "Nehemiah 8:10 — The joy of the Lord is your strength.",
  "Esther 4:14 — Who knows if you have come to the kingdom for such a time as this?",
  "Job 1:21 — The Lord gave and the Lord has taken away.",
  "Psalm 23:1 — The Lord is my shepherd; I shall not want.",
  "Psalm 46:1 — God is our refuge and strength.",
  "Psalm 119:105 — Your word is a lamp to my feet.",
  "Proverbs 3:5 — Trust in the Lord with all your heart.",
  "Proverbs 18:10 — The name of the Lord is a strong tower.",
  "Ecclesiastes 3:1 — To everything there is a season.",
  "Song of Solomon 2:1 — I am the rose of Sharon.",
  "Isaiah 40:31 — Those who hope in the Lord will renew their strength.",
  "Isaiah 41:10 — Do not fear, for I am with you.",
  "Isaiah 53:5 — He was pierced for our transgressions.",
  "Jeremiah 29:11 — I know the plans I have for you.",
  "Lamentations 3:22 — The steadfast love of the Lord never ceases.",
  "Ezekiel 36:26 — I will give you a new heart.",
  "Daniel 3:17 — Our God whom we serve is able.",
  "Hosea 6:6 — I desire mercy, not sacrifice.",
  "Joel 2:28 — I will pour out my Spirit on all people.",
  "Amos 5:24 — Let justice roll on like a river.",
  "Obadiah 1:15 — The day of the Lord is near.",
  "Jonah 2:2 — I called out to the Lord, and he answered me.",
  "Micah 6:8 — Act justly, love mercy, walk humbly.",
  "Nahum 1:7 — The Lord is good, a refuge in times of trouble.",
  "Habakkuk 3:19 — The Lord is my strength.",
  "Zephaniah 3:17 — The Lord your God is with you.",
  "Haggai 2:9 — The glory of this present house will be greater.",
  "Zechariah 4:6 — Not by might nor by power, but by my Spirit.",
  "Malachi 3:10 — Bring the whole tithe into the storehouse.",
  "Matthew 5:16 — Let your light shine before others.",
  "Matthew 6:33 — Seek first the kingdom of God.",
  "Matthew 11:28 — Come to me, all who are weary.",
  "Mark 10:27 — With God all things are possible.",
  "Luke 1:37 — For nothing will be impossible with God.",
  "Luke 6:31 — Do to others as you would have them do to you.",
  "John 1:1 — In the beginning was the Word.",
  "John 3:16 — For God so loved the world.",
  "John 8:12 — I am the light of the world.",
  "John 14:6 — I am the way, the truth, and the life.",
  "Acts 1:8 — You will receive power when the Holy Spirit comes.",
  "Romans 8:28 — All things work together for good.",
  "Romans 12:2 — Do not conform to the pattern of this world.",
  "1 Corinthians 13:4 — Love is patient, love is kind.",
  "2 Corinthians 5:17 — If anyone is in Christ, new creation.",
  "Galatians 5:22 — The fruit of the Spirit is love, joy, peace.",
  "Ephesians 2:8 — By grace you have been saved.",
  "Philippians 4:13 — I can do all things through Christ.",
  "Colossians 3:23 — Work heartily, as for the Lord.",
  "1 Thessalonians 5:16 — Rejoice always.",
  "2 Timothy 1:7 — God gave us a spirit of power.",
  "Hebrews 11:1 — Faith is the assurance of things hoped for.",
  "James 1:5 — If any lacks wisdom, ask God.",
  "1 Peter 5:7 — Cast all your anxiety on him.",
  "2 Peter 1:5 — Make every effort to add to your faith.",
  "1 John 4:18 — Perfect love casts out fear.",
  "Revelation 3:20 — I stand at the door and knock.",
  "Revelation 21:4 — He will wipe every tear away.",
  "Psalm 27:1 — The Lord is my light and salvation.",
  "Psalm 34:8 — Taste and see that the Lord is good.",
  "Psalm 91:1 — He who dwells in the shelter of the Most High.",
  "Isaiah 26:3 — You will keep in perfect peace.",
  "Isaiah 43:2 — When you pass through the waters.",
  "Jeremiah 33:3 — Call to me and I will answer you.",
  "Matthew 28:19 — Go and make disciples of all nations.",
  "Mark 12:30 — Love the Lord your God with all your heart.",
  "Luke 9:23 — Take up your cross daily.",
  "John 15:5 — I am the vine; you are the branches.",
  "Romans 10:9 — Confess with your mouth, believe in your heart.",
  "1 Corinthians 10:13 — No temptation has overtaken you except what is common.",
  "Galatians 2:20 — I have been crucified with Christ.",
  "Ephesians 6:11 — Put on the full armor of God.",
  "Philippians 1:6 — He who began a good work in you.",
  "Colossians 3:12 — Clothe yourselves with compassion.",
  "1 Thessalonians 5:24 — Faithful is he who calls you.",
  "Hebrews 13:8 — Jesus Christ is the same yesterday and today.",
  "James 4:7 — Submit yourselves to God.",
  "1 Peter 3:15 — Always be prepared to give an answer.",
  "Revelation 22:13 — I am the Alpha and the Omega."
];

const verseText = document.getElementById("verse");
const button = document.getElementById("verseBtn");

button.addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * verses.length);
  verseText.textContent = verses[randomIndex];
});